//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NadekoBot.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorStrings_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ErrorStrings_en() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NadekoBot.Resources.ErrorStrings_en", typeof(ErrorStrings_en).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ⚠️ **Error.** Most likely I don&apos;t have sufficient permissions..
        /// </summary>
        public static string Ban {
            get {
                return ResourceManager.GetString("Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ⚠️ I most likely don&apos;t have the permission necessary for that..
        /// </summary>
        public static string ChatMute {
            get {
                return ResourceManager.GetString("ChatMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ⚠️ I most likely don&apos;t have the permission necessary for that..
        /// </summary>
        public static string ChatUnmute {
            get {
                return ResourceManager.GetString("ChatUnmute", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 【CreateRole】: ⚠️ Unspecified error..
        /// </summary>
        public static string CreateRole {
            get {
                return ResourceManager.GetString("CreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ⚠️ I most likely don&apos;t have the permission necessary for that..
        /// </summary>
        public static string Deafen {
            get {
                return ResourceManager.GetString("Deafen", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 【DelMsgOnCmd_Handler】: ❗ Delmsgoncmd errored....
        /// </summary>
        public static string DelMsgOnCmd_Handler {
            get {
                return ResourceManager.GetString("DelMsgOnCmd_Handler", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ⚠️ Error. Most likely I don&apos;t have sufficient permissions..
        /// </summary>
        public static string Kick {
            get {
                return ResourceManager.GetString("Kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 【RemoveAllRoles】: ⚠️ Failed to remove roles. Most likely reason: **Insufficient permissions.**.
        /// </summary>
        public static string RemoveAllRoles {
            get {
                return ResourceManager.GetString("RemoveAllRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ⚠️ Failed to remove role. Most likely reason: **Insufficient permissions.**.
        /// </summary>
        public static string Removerole {
            get {
                return ResourceManager.GetString("Removerole", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ⚠️ Failed to rename role. Probably **insufficient permissions.**.
        /// </summary>
        public static string RenameRole {
            get {
                return ResourceManager.GetString("RenameRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ⚠️ Error occured, most likely **invalid parameters** or **insufficient permissions.**.
        /// </summary>
        public static string RoleColor {
            get {
                return ResourceManager.GetString("RoleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ⚠️ Invalid format..
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ⚠️ I most likely don&apos;t have the permission necessary for that..
        /// </summary>
        public static string SetMuteRole {
            get {
                return ResourceManager.GetString("SetMuteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ⚠️ Failed to add role. **Bot has insufficient permissions.**\n.
        /// </summary>
        public static string Setrole {
            get {
                return ResourceManager.GetString("Setrole", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ⚠️ Error. Most likely I don&apos;t have sufficient permissions..
        /// </summary>
        public static string Softban {
            get {
                return ResourceManager.GetString("Softban", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ⚠️ I most likely don&apos;t have the permission necessary for that..
        /// </summary>
        public static string UnDeafen {
            get {
                return ResourceManager.GetString("UnDeafen", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ⚠️ I most likely don&apos;t have the permission necessary for that..
        /// </summary>
        public static string Unmute {
            get {
                return ResourceManager.GetString("Unmute", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ⚠️ I most likely don&apos;t have the permission necessary for that..
        /// </summary>
        public static string VoiceMute {
            get {
                return ResourceManager.GetString("VoiceMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ⚠️ I most likely don&apos;t have the permission necessary for that..
        /// </summary>
        public static string VoiceUnmute {
            get {
                return ResourceManager.GetString("VoiceUnmute", resourceCulture);
            }
        }
    }
}
