//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NadekoBot.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SuccessStrings_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal SuccessStrings_en() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NadekoBot.Resources.SuccessStrings_en", typeof(SuccessStrings_en).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 🆕 **Message from {0} `(Bot Owner)`:** {1}.
        /// </summary>
        public static string Announce {
            get {
                return ResourceManager.GetString("Announce", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ⛔️ **Banned** user **{0}** ID: `{1}`.
        /// </summary>
        public static string Ban {
            get {
                return ResourceManager.GetString("Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ⛔️ **You have been BANNED from `{0}` server.**
        ///⚖ *Reason:* {1}.
        /// </summary>
        public static string Ban_DM {
            get {
                return ResourceManager.GetString("Ban_DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ✏️🚫 **{0}** has been **muted** from chatting successfully..
        /// </summary>
        public static string ChatMute {
            get {
                return ResourceManager.GetString("ChatMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ✏️✅ **{0}** has been **unmuted** from chatting successfully..
        /// </summary>
        public static string ChatUnmute {
            get {
                return ResourceManager.GetString("ChatUnmute", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ✅ Successfully created role **{0}**..
        /// </summary>
        public static string CreateRole {
            get {
                return ResourceManager.GetString("CreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ✅ Created voice channel **{0}**. ID: `{1}`.
        /// </summary>
        public static string CreatVoiChanl {
            get {
                return ResourceManager.GetString("CreatVoiChanl", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ✅ Added text channel **{0}**. ID: `{1}`.
        /// </summary>
        public static string CreaTxtChanl {
            get {
                return ResourceManager.GetString("CreaTxtChanl", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 🔇 **Deafen** successful..
        /// </summary>
        public static string Deafen {
            get {
                return ResourceManager.GetString("Deafen", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ✅ **Now automatically deleting successful command invokations.**.
        /// </summary>
        public static string Delmsgoncmd {
            get {
                return ResourceManager.GetString("Delmsgoncmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 🗑 Removed text channel **{0}**. ID: `{1}`.
        /// </summary>
        public static string DelTxtChanl {
            get {
                return ResourceManager.GetString("DelTxtChanl", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 🗑 Removed voice channel **{0}** successfully..
        /// </summary>
        public static string DelVoiChanl {
            get {
                return ResourceManager.GetString("DelVoiChanl", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ℹ️ **Shutting down.**.
        /// </summary>
        public static string Die {
            get {
                return ResourceManager.GetString("Die", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Successfuly added a new donator. Total donated amount from this user: {0} 👑.
        /// </summary>
        public static string Donadd {
            get {
                return ResourceManager.GetString("Donadd", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to **Thanks to the people listed below for making this project happen!**
        ///{0}
        ///`Patreon supporters:`
        ///{1}.
        /// </summary>
        public static string Donators {
            get {
                return ResourceManager.GetString("Donators", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ‼️**Kicked** user **{0}** ID: `{1}`.
        /// </summary>
        public static string Kick {
            get {
                return ResourceManager.GetString("Kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ‼️**You have been KICKED from `{0}` server.**
        ///⚖ *Reason:* {1}.
        /// </summary>
        public static string Kick_DM {
            get {
                return ResourceManager.GetString("Kick_DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ❕{0} __`has invoked a mention on the following roles`__❕
        ///**{1}**
        ///{2}.
        /// </summary>
        public static string MentionRole {
            get {
                return ResourceManager.GetString("MentionRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 🔇 **{0}** has been **muted** from text and voice chat successfully..
        /// </summary>
        public static string Mute {
            get {
                return ResourceManager.GetString("Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 🗑 Successfully removed **all** roles from user **{0}**.
        /// </summary>
        public static string RemoveAllRoles {
            get {
                return ResourceManager.GetString("RemoveAllRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ℹ️ Successfully removed role **{0}** from user **{1}**.
        /// </summary>
        public static string Removerole {
            get {
                return ResourceManager.GetString("Removerole", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ✅ Role renamed..
        /// </summary>
        public static string RenameRole {
            get {
                return ResourceManager.GetString("RenameRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} 🆗 **Permissions for this server are reset.**.
        /// </summary>
        public static string ResetPermissions {
            get {
                return ResourceManager.GetString("ResetPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ☑️ Role **{0}&apos;s** color has been changed..
        /// </summary>
        public static string RoleColor {
            get {
                return ResourceManager.GetString("RoleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 🆒 **New avatar set.**.
        /// </summary>
        public static string SetAvatar {
            get {
                return ResourceManager.GetString("SetAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 🆗 **New channel name set.**.
        /// </summary>
        public static string SetChanlName {
            get {
                return ResourceManager.GetString("SetChanlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 👾 **New game set.**.
        /// </summary>
        public static string SetGame {
            get {
                return ResourceManager.GetString("SetGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ☑️ **New mute role set.**.
        /// </summary>
        public static string SetMuteRole {
            get {
                return ResourceManager.GetString("SetMuteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ℹ️ Successfully changed name to **{0}**.
        /// </summary>
        public static string Setname {
            get {
                return ResourceManager.GetString("Setname", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ℹ️ Successfully added role **{0}** to user **{1}**.
        /// </summary>
        public static string Setrole {
            get {
                return ResourceManager.GetString("Setrole", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ℹ️ **New stream set.**.
        /// </summary>
        public static string SetStream {
            get {
                return ResourceManager.GetString("SetStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 🆗 **New channel topic set.**.
        /// </summary>
        public static string SetTopic {
            get {
                return ResourceManager.GetString("SetTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ☣ **Soft-Banned** user **{0}** ID: `{1}`.
        /// </summary>
        public static string Softban {
            get {
                return ResourceManager.GetString("Softban", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ☣ **You have been SOFT-BANNED from `{0}` server.**
        ///⚖ *Reason:* {1}.
        /// </summary>
        public static string Softban_DM {
            get {
                return ResourceManager.GetString("Softban_DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 🔊 **Undeafen** successful..
        /// </summary>
        public static string UnDeafen {
            get {
                return ResourceManager.GetString("UnDeafen", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 🔉 **{0}** has been **unmuted** from text and voice chat successfully..
        /// </summary>
        public static string Unmute {
            get {
                return ResourceManager.GetString("Unmute", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 🎙🚫 **{0}** has been **voice muted** successfully..
        /// </summary>
        public static string VoiceMute {
            get {
                return ResourceManager.GetString("VoiceMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 🎙✅ **{0}** has been **voice unmuted** successfully..
        /// </summary>
        public static string VoiceUnmute {
            get {
                return ResourceManager.GetString("VoiceUnmute", resourceCulture);
            }
        }
    }
}
